import { Icon, Status } from '../components/ui'
import type { DashboardData } from '../api/dashboard'
import type { Subscription } from '../types/portal'
import { useCurrency } from '../contexts/CurrencyContext'

export function DashboardPage({ items, dashboard, onBudgets }: { items: Subscription[]; dashboard: DashboardData; onBudgets: () => void }) {
  const { format } = useCurrency()
  return <><section className="stat-grid"><div className="stat-card"><div><span>Total spend this month</span><Status>On track</Status></div><strong>{format(dashboard.monthlySpend)}</strong><p>Live from subscription records</p></div><div className="stat-card"><div><span>Active subscriptions</span><Icon name="card" /></div><strong>{dashboard.activeSubscriptions}</strong><p>Across {dashboard.projects.length} projects</p></div><div className="stat-card"><div><span>Renewing in 30 days</span><Status tone="amber">Attention</Status></div><strong>{dashboard.upcomingRenewals}</strong><p>From the renewal calendar</p></div><div className="stat-card"><div><span>Projects over budget</span><Status tone="red">Review</Status></div><strong>{dashboard.projects.filter((project) => project.monthlyBudget !== null && project.spend > project.monthlyBudget).length}</strong><p>Based on current monthly spend</p></div></section><section className="grid-two"><article className="panel"><div className="panel-title"><div><h2>Budget overview</h2><p>Monthly spend against project budgets</p></div><button className="link" onClick={onBudgets}>Manage budgets →</button></div>{dashboard.projects.map((project) => { const percent = project.monthlyBudget ? Math.round((project.spend / project.monthlyBudget) * 100) : 0; return <div className="budget-row" key={project.id}><div className="project-name"><span className="project-icon purple">{project.name.slice(0, 2).toUpperCase()}</span><span><strong>{project.name}</strong><small>Live project total</small></span></div><div className="budget-value"><strong>{format(project.spend)}</strong><small>{project.monthlyBudget ? `of ${format(project.monthlyBudget)}` : 'no budget set'}</small></div><div className="bar"><i className={percent > 80 ? 'amber-bar' : ''} style={{ width: `${Math.min(percent || 8, 100)}%` }} /></div><Status tone={project.monthlyBudget ? (percent > 80 ? 'amber' : 'green') : 'amber'}>{project.monthlyBudget ? `${percent}% used` : 'Set budget'}</Status></div> })}</article><article className="panel"><div className="panel-title"><div><h2>Spend by service</h2><p>Current monthly run rate</p></div></div>{items.slice(0, 4).map((item) => <div className="service-bar-row" key={item.id}><span><i className={`dot ${item.tone}`} />{item.service}</span><strong>{format(item.usd)}</strong><div className="bar"><i style={{ width: `${Math.min(item.usd / 5, 90)}%` }} /></div></div>)}</article></section><section className="panel renewals"><div className="panel-title"><div><h2>Renewing soon</h2><p>Subscriptions renewing in the next 30 days</p></div></div><table><thead><tr><th>SERVICE</th><th>PROJECT</th><th>RENEWAL DATE</th><th>MONTHLY COST</th><th>STATUS</th></tr></thead><tbody>{items.slice(0, 4).map((item) => <tr key={item.id}><td><strong>{item.service}</strong></td><td>{item.project}</td><td>{item.renewal}</td><td><strong>{format(item.usd)}</strong></td><td><Status tone="amber">Renewal tracked</Status></td></tr>)}</tbody></table></section></>
}
