import { useState, type ReactNode } from 'react'
import { Icon, Status } from '../components/ui'
import type { Seat } from '../api/seats'
import type { Invoice } from '../api/invoices'
import type { WorkspaceUser } from '../api/users'
import { chipTone } from '../utils/chip'
import { useCurrency } from '../contexts/CurrencyContext'

export function SeatsPage({ data }: { data: Seat[] }) { return <section className="panel table-panel"><PageTitle title="Assigned seats" description={`${data.length} assigned seats from the API`} /><div className="filters"><label><Icon name="search" /><input placeholder="Search people or services" /></label><select><option>All projects</option><option>New Dawn</option><option>ECDS</option></select></div><Table><thead><tr><th>PERSON</th><th>EMAIL</th><th>SUBSCRIPTION</th><th>PROJECT</th><th>LICENSE TYPE</th><th>ASSIGNED DATE</th></tr></thead><tbody>{data.map((seat) => { const serviceName = seat.subscription?.serviceName ?? 'Subscription'; const project = seat.project ?? 'Project'; return <tr key={seat.id}><td><strong>{seat.name}</strong></td><td>{seat.email}</td><td><span className={`chip ${chipTone(serviceName)}`}>{serviceName}</span></td><td><span className={`chip ${chipTone(project)}`}>{project}</span></td><td><span className={`chip ${chipTone(seat.licenseType)}`}>{seat.licenseType === 'TEAM' ? 'Team license' : 'Individual license'}</span></td><td>{new Date(seat.assignedAt).toLocaleDateString()}</td></tr> })}</tbody></Table></section> }
export function InvoicesPage({ data }: { data: Invoice[] }) {
  const { format } = useCurrency()
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const allSelected = data.length > 0 && selected.size === data.length
  const toggleAll = () => setSelected(allSelected ? new Set() : new Set(data.map((invoice) => invoice.id)))
  const toggleOne = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next })
  const downloadSelected = () => {
    const rows = data.filter((invoice) => selected.has(invoice.id))
    const header = 'File,Subscription,Project,Period,Amount,Status'
    const csv = [header, ...rows.map((invoice) => [invoice.fileName, invoice.serviceName, invoice.project, invoice.billingPeriod, invoice.amount, invoice.autoGenerated ? 'Awaiting upload' : `Uploaded ${invoice.invoiceDate}`].join(','))].join('\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
    const link = document.createElement('a')
    link.href = url
    link.download = 'invoices.csv'
    link.click()
    URL.revokeObjectURL(url)
  }
  return <section className="panel table-panel"><PageTitle title="Invoices" description={`${data.length} invoices auto-fetched from this month's subscriptions`} action={selected.size ? `⇩ Download selected (${selected.size})` : '⇩ Download selected'} onAction={downloadSelected} disabled={selected.size === 0} /><div className="filters"><label><Icon name="search" /><input placeholder="Search invoice number or service" /></label><select><option>All projects</option><option>New Dawn</option><option>ECDS</option></select><input className="date-input" type="date" /><input className="date-input" type="date" /></div><Table><thead><tr><th className="th-check"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Select all invoices" /></th><th>FILE</th><th>SUBSCRIPTION</th><th>PROJECT</th><th>PERIOD</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{data.map((invoice) => <tr key={invoice.id}><td><input type="checkbox" checked={selected.has(invoice.id)} onChange={() => toggleOne(invoice.id)} aria-label={`Select ${invoice.fileName}`} /></td><td><strong>{invoice.fileName}</strong></td><td><span className={`chip ${chipTone(invoice.serviceName)}`}>{invoice.serviceName}</span></td><td><span className={`chip ${chipTone(invoice.project)}`}>{invoice.project}</span></td><td>{invoice.billingPeriod}</td><td><strong>{format(Number(invoice.amount))}</strong></td><td>{invoice.autoGenerated ? <Status tone="amber">Awaiting upload</Status> : <Status tone="green">{`Uploaded ${invoice.invoiceDate}`}</Status>}</td></tr>)}</tbody></Table></section>
}
export function UsersPage({ data }: { data: WorkspaceUser[] }) { return <section className="panel table-panel"><PageTitle title="Workspace users" description={`${data.length} users from the API`} action="＋ Invite user" /><Table><thead><tr><th>USER</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>{data.map((user) => <tr key={user.id}><td><div className="cell-stack"><strong>{user.name}</strong><small>{user.email}</small></div></td><td><span className={`chip ${chipTone(user.role)}`}>{user.role}</span></td><td><Status>Active</Status></td></tr>)}</tbody></Table></section> }
function PageTitle({ title, description, action, onAction, disabled }: { title: string; description: string; action?: string; onAction?: () => void; disabled?: boolean }) { return <div className="panel-title"><div><h2>{title}</h2><p>{description}</p></div>{action && <button className="button primary" onClick={onAction} disabled={disabled}>{action}</button>}</div> }
function Table({ children }: { children: ReactNode }) { return <div className="table-wrap"><table>{children}</table></div> }
