import { apiRequest } from './client'

const MAX_INVOICE_BYTES = 2 * 1024 * 1024

export type Invoice = { id: string; invoiceNumber: string; billingPeriod: string; fileName: string; fileUrl: string | null; amount: number; invoiceDate: string; subscriptionId: string; project: string; serviceName: string; autoGenerated: boolean }

export function listInvoices(month: string, subscriptionId?: string) { return apiRequest<{ data: Invoice[] }>(`/invoices?month=${encodeURIComponent(month)}${subscriptionId ? `&subscriptionId=${encodeURIComponent(subscriptionId)}` : ''}`) }

export async function uploadInvoice(subscriptionId: string, month: string, file: File) {
  if (file.type !== 'application/pdf') throw new Error('Only PDF files are allowed')
  if (file.size > MAX_INVOICE_BYTES) throw new Error('File must be 2MB or smaller')
  const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:4000/api'
  const token = localStorage.getItem('ec-labs-auth-token')
  const body = new FormData()
  body.append('month', month)
  body.append('file', file)
  const response = await fetch(`${apiBaseUrl}/subscriptions/${subscriptionId}/invoices`, { method: 'POST', headers: token ? { Authorization: `Bearer ${token}` } : undefined, body })
  if (!response.ok) { const payload = await response.json().catch(() => null); throw new Error(payload?.error ?? `Upload failed: ${response.status}`) }
  return response.json() as Promise<{ data: { id: string; subscriptionId: string; fileUrl: string; fileName: string } }>
}
