import { apiRequest } from './client'

export type Invoice = { id: string; invoiceNumber: string; billingPeriod: string; fileName: string; amount: number; invoiceDate: string; subscriptionId: string; project: string; serviceName: string; autoGenerated: boolean }
export function listInvoices(month: string, subscriptionId?: string) { return apiRequest<{ data: Invoice[] }>(`/invoices?month=${encodeURIComponent(month)}${subscriptionId ? `&subscriptionId=${encodeURIComponent(subscriptionId)}` : ''}`) }
export function createInvoice(input: Omit<Invoice, 'id'>) { return apiRequest<{ data: Invoice }>('/invoices', { method: 'POST', body: JSON.stringify(input) }) }
export function invoiceExportUrl() { return `${import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:4000/api'}/export/subscriptions.csv` }
